# cmd_args:
#   batch_size: 256
#   dev_batch_factor: 2
#   device_ids: 0,1,2,3
#   distributed: torch
#   epochs: 100
#   eval_interval: 2000
#   init: ''
#   num_workers: 16
#   prog_interval: 100
#   resume: ''
#   save_interval: -1
#   seed: '888'
#   tensorboard: false
#   trainer: ddp

nnet: "asr@att"

nnet_conf:
  input_size: 80
  enc_type: "concat"
  enc_proj: 800
  enc_kwargs:
    conv2d:
      out_features: -1
      in_channels: 1
      channel: 64
      num_layers: 2
      stride: 2
      padding: 1
      kernel_size: 3
    pytorch_rnn:
      bidirectional: true
      dropout: 0.2
      hidden: 512
      num_layers: 4
  dec_dim: 512
  dec_kwargs:
    dec_rnn: "lstm"
    rnn_layers: 2
    rnn_hidden: 512
    rnn_dropout: 0.1
    emb_dropout: 0.2
    input_feeding: false
  att_type: "ctx"
  att_kwargs:
    att_dim: 512

task: "asr@ctc_xent"

task_conf:
  reduction: batchmean
  ctc_weight: 0.2
  lsm_factor: 0.1
  lsm_method: unigram
  label_count: data/librispeech/train/label_count

asr_transform:
  feats: "perturb-fbank-log-aug"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  round_pow_of_two: true
  use_power: true
  pre_emphasis: 0.97
  audio_norm: false
  sr: 16000
  num_mels: 80
  min_freq: 20
  aug_prob: 1
  aug_maxp_time: 1
  aug_freq_args: [27, 2]
  aug_time_args: [100, 2]
  aug_mask_zero: false

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 0.0
    weight_decay: 1.0e-5
  lr_scheduler: "warmup_exp_decay_lr"
  lr_scheduler_period: "step"
  lr_scheduler_kwargs:
    time_stamps: [1000, 60000, 160000]
    peak_lr: 1.0e-3
    stop_lr: 1.0e-6
  no_impr: 10
  no_impr_thres: 0.01
  clip_gradient: 5
  acmu_gradient: 4
  report_metrics: ["loss", "accu", "@ctc"]
  stop_criterion: "accu"


data_conf:
  fmt: "am@raw"
  loader:
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
    max_token_num: 400
    adapt_token_num: 200
  train:
    text: data/librispeech/train/token
    utt2dur: data/librispeech/train/utt2dur
    wav_scp: data/librispeech/train/wav.scp
  valid:
    text: data/librispeech/dev/token
    utt2dur: data/librispeech/dev/utt2dur
    wav_scp: data/librispeech/dev/wav.scp
