#!/usr/bin/env perl
# wujian@2018
#
use utf8;

use open qw(:encoding(utf8));
binmode STDIN, ":utf8";
binmode STDOUT, ":utf8";
binmode STDERR, ":utf8";

while (<>) {
  @F = split " ";
  $cs = $F[0];
  foreach $s (@F[1..$#F]) {
    @s = split("", $s);
    foreach $c (@s) {
        $cs = "$cs $c";
    }
  }
  print "$cs\n";
}