# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: ''
    hooks:
    -   id: yapf
        language: python
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: ''
    hooks:
    -   id: clang-format
