nnet: "asr@xfmr"

nnet_conf:
  input_size: 80
  enc_type: "xfmr_rel"
  enc_kwargs:
    proj_layer: "conv2d"
    proj_kwargs:
      conv_channels: 256
    att_dim: 512
    radius: 256
    nhead: 8
    feedforward_dim: 1024
    pos_dropout: 0.1
    att_dropout: 0.2
    ffn_dropout: 0.2
    num_layers: 12
    post_norm: false
  dec_type: "xfmr_abs"
  dec_kwargs:
    att_dim: 512
    nhead: 8
    feedforward_dim: 1024
    pos_dropout: 0.1
    att_dropout: 0.2
    ffn_dropout: 0.2
    num_layers: 6
    scale_embed: false
    post_norm: false

task: "asr@ctc_xent"

task_conf:
  reduction: batchmean
  lsm_factor: 0.1
  lsm_method: uniform
  ctc_weight: 0.3

asr_transform:
  feats: "cmvn-aug"
  sr: 16000
  norm_mean: true
  norm_var: true
  gcmvn: "data/aishell_v1/train_sp/cmvn.ark"
  aug_prob: 1
  aug_maxp_time: 0.6
  aug_mask_zero: false
  aug_freq_args: [27, 1]
  aug_time_args: [80, 1]

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 0.0
    weight_decay: 1.0e-6
    betas: [0.9, 0.98]
    eps: 1.0e-9
  lr_scheduler: "warmup_noam_lr"
  lr_scheduler_period: "step"
  lr_scheduler_kwargs:
    transformer_dim: 256
    warmup: 20000
    peak_lr: -1
  no_impr: -1
  no_impr_thres: 0
  clip_gradient: 5
  report_metrics: ["loss", "accu"]
  stop_criterion: "accu"

data_conf:
  fmt: "am@kaldi"
  loader:
    max_dur: 3000
    min_dur: 10
    adapt_dur: 1000
    max_token_num: 400
    adapt_token_num: 200
  train:
    feats_scp: "data/aishell_v1/train_sp/feats.scp"
    utt2num_frames: "data/aishell_v1/train_sp/utt2num_frames"
    text: "aishell_v1/train_sp/text"
  valid:
    feats_scp: "data/aishell_v1/dev/feats.scp"
    utt2num_frames: "data/aishell_v1/dev/utt2num_frames"
    text: "data/aishell_v1/dev/text"
