nnet: "asr@transducer"

nnet_conf:
  input_size: 80
  enc_type: "concat"
  enc_proj: 512
  enc_kwargs:
    conv2d:
      out_features: -1
      channel: 32
      num_layers: 2
      stride: 2
      padding: 1
      kernel_size: 3
    variant_rnn:
      rnn: "lstm"
      num_layers: 3
      bidirectional: true
      dropout: 0.2
      project: 512
      hidden: 512
      norm: "LN"
  dec_kwargs:
    embed_size: 512
    jot_dim: 512
    dec_rnn: "lstm"
    dec_layers: 3
    dec_hidden: 512
    dec_dropout: 0.2

task: "asr@transducer"

asr_transform:
  feats: "fbank-log-cmvn-aug"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  pre_emphasis: 0.96
  round_pow_of_two: True
  sr: 16000
  num_mels: 80
  norm_mean: True
  norm_var: True
  aug_prob: 0.5

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-5
  lr_scheduler: "reduce_lr"
  lr_scheduler_period: "epoch"
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 6
  no_impr_thres: 0.3
  clip_gradient: 50
  report_metrics: ["loss"]
  stop_criterion: "loss"

data_conf:
  fmt: "am@raw"
  loader:
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
    max_token_num: 400
    adapt_token_num: 150
  train:
    wav_scp: "data/aishell_v1/train/wav.scp"
    utt2dur: "data/aishell_v1/train/utt2dur"
    text: "data/aishell_v1/train/text"
  valid:
    wav_scp: "data/aishell_v1/dev/wav.scp"
    utt2dur: "data/aishell_v1/dev/utt2dur"
    text: "data/aishell_v1/dev/text"
