# cmd_args:
#   batch_size: 256
#   device_id: '0'
#   epochs: 100
#   eval_interval: 5000
#   init: ''
#   num_workers: 0
#   prog_interval: 100
#   resume: ''
#   save_interval: -1
#   seed: '888'
#   tensorboard: false
#   trainer: ddp

nnet: "asr@rnn_lm"

nnet_conf:
  embed_size: 1024
  tie_weights: true
  rnn: lstm
  dropout: 0.2
  num_layers: 3
  hidden_size: 1024

task: "asr@lm"

task_conf:
  bptt_mode: true

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 8
  no_impr_thres: 0
  clip_gradient: 10
  report_metrics: ["loss", "accu", "@ppl"]
  stop_criterion: "loss"

data_conf:
  fmt: "lm@bptt"
  loader:
    kaldi_format: false
    bptt_size: 128
    min_token_num: 20
    max_token_num: 300
  train:
    text: "data/librispeech/lm/train.token"
  valid:
    text: "data/librispeech/lm/dev.token"
