# cmd_args:
#   batch_size: 32
#   dev_batch_factor: 2
#   device_ids: '0'
#   dict: data/timit/dict
#   distributed: none
#   epochs: 100
#   eval_interval: -1
#   init: ''
#   num_workers: 4
#   prog_interval: 100
#   resume: ''
#   save_interval: -1
#   seed: '777'
#   tensorboard: false
#   trainer: ddp

nnet: "asr@att"

nnet_conf:
  input_size: 240
  enc_type: "variant_rnn"
  enc_proj: 512
  enc_kwargs:
    rnn: "lstm"
    hidden: 320
    num_layers: 3
    bidirectional: true
    dropout: 0.2
    project: 512
  dec_dim: 512
  dec_kwargs:
    dec_rnn: "lstm"
    rnn_layers: 2
    rnn_hidden: 512
    rnn_dropout: 0.2
    emb_dropout: 0.2
    input_feeding: true
  att_type: "loc"
  att_kwargs:
    att_dim: 256
    conv_channels: 10
    loc_context: 100

task: "asr@ctc_xent"

task_conf:
  lsm_factor: 0.1
  ctc_weight: 0.2

asr_transform:
  feats: "perturb-fbank-log-cmvn-delta"
  frame_len: 400
  frame_hop: 160
  audio_norm: false
  pre_emphasis: 0.96
  window: "hamm"
  round_pow_of_two: true
  sr: 16000
  num_mels: 80

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 6
  no_impr_thres: 0.1
  clip_gradient: 1
  report_metrics: ["loss", "accu", "@ctc"]
  stop_criterion: "accu"

data_conf:
  fmt: "am@raw"
  loader:
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
    max_token_num: 400
    adapt_token_num: 150
  train:
    wav_scp: "data/timit/train/wav.scp"
    utt2dur: "data/timit/train/utt2dur"
    text: "data/timit/train/text"
  valid:
    wav_scp: "data/timit/dev/wav.scp"
    utt2dur: "data/timit/dev/utt2dur"
    text: "data/timit/dev/text"
