nnet: "asr@transducer"

nnet_conf:
  input_size: 240
  enc_type: "variant_rnn"
  enc_proj: 512
  enc_kwargs:
    rnn: "lstm"
    norm: "BN"
    hidden: 512
    dropout: 0.2
    project: 512
    num_layers: 3
    bidirectional: true
  dec_kwargs:
    embed_size: 512
    jot_dim: 512
    dec_rnn: "lstm"
    dec_layers: 2
    dec_hidden: 512
    dec_dropout: 0.2

task: "asr@transducer"

asr_transform:
  feats: "perturb-fbank-log-cmvn-delta"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  audio_norm: false
  round_pow_of_two: true
  pre_emphasis: 0.96
  sr: 16000
  num_mels: 80

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  no_impr: 6
  no_impr_thres: 0.001
  clip_gradient: 1
  report_metrics: ["loss"]
  stop_criterion: "loss"

data_conf:
  fmt: "am@raw"
  loader:
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
    max_token_num: 400
    adapt_token_num: 150
  train:
    wav_scp: "data/timit/train/wav.scp"
    utt2dur: "data/timit/train/utt2dur"
    text: "data/timit/train/text"
  valid:
    wav_scp: "data/timit/dev/wav.scp"
    utt2dur: "data/timit/dev/utt2dur"
    text: "data/timit/dev/text"
