# cmd_args:
#   batch_size: 96
#   dev_batch_factor: 2
#   device_ids: 0,1,2,3
#   distributed: torch
#   epochs: 100
#   eval_interval: 2500
#   init: ''
#   num_workers: 16
#   prog_interval: 100
#   resume: ''
#   save_interval: -1
#   seed: '888'
#   tensorboard: false
#   trainer: ddp

nnet: "asr@xfmr"

nnet_conf:
  input_size: 80
  enc_type: "xfmr_rel"
  enc_kwargs:
    proj_layer: "conv2d"
    proj_kwargs:
      conv_channels: 128
    att_dim: 512
    radius: 512
    nhead: 8
    feedforward_dim: 1024
    pos_dropout: 0.2
    att_dropout: 0.2
    num_layers: 12
    post_norm: false
  dec_kwargs:
    att_dim: 512
    nhead: 8
    feedforward_dim: 1024
    pos_dropout: 0.2
    att_dropout: 0.2
    num_layers: 6
    post_norm: false

task: "asr@ctc_xent"

task_conf:
  lsm_factor: 0.1
  lsm_method: "unigram"
  ctc_weight: 0.2
  label_count: "data/librispeech/train/label_count"

asr_transform:
  feats: "perturb-fbank-log-cmvn-aug"
  frame_len: 400
  frame_hop: 160
  window: "hamm"
  round_pow_of_two: true
  use_power: true
  pre_emphasis: 0.97
  audio_norm: false
  sr: 16000
  num_mels: 80
  min_freq: 20
  norm_mean: true
  norm_var: true
  norm_per_band: false
  aug_prob: 1
  aug_freq_args: [27, 2]
  aug_time_args: [100, 2]
  aug_mask_zero: false

trainer_conf:
  optimizer: "adamw"
  optimizer_kwargs:
    lr: 0.0
    weight_decay: 1.0e-2
  lr_scheduler: "warmup_noam_lr"
  lr_scheduler_period: "step"
  lr_scheduler_kwargs:
    transformer_dim: 512
    peak_lr: -1
    warmup: 20000
  no_impr: 8
  no_impr_thres: 0
  clip_gradient: 5
  acmu_gradient: 4
  report_metrics: ["loss", "accu", "@ctc"]
  stop_criterion: "accu"

data_conf:
  fmt: "am@raw"
  loader:
    max_dur: 30 # (s)
    min_dur: 0.4 # (s)
    adapt_dur: 10 # (s)
    min_batch_size: 4
    max_token_num: 400
    adapt_token_num: 100
  train:
    text: data/librispeech/train/token
    utt2dur: data/librispeech/train/utt2dur
    wav_scp: data/librispeech/train/wav.scp
  valid:
    text: data/librispeech/dev/token
    utt2dur: data/librispeech/dev/utt2dur
    wav_scp: data/librispeech/dev/wav.scp
