# DPRNN

nnet: sse@time_dprnn

nnet_conf:
  num_spks: 2
  kernel: 8
  stride: 4
  num_bins: 64
  chunk_size: 150
  num_layers: 6
  rnn_hidden: 128

task: "sse@sisnr"

task_conf:
  num_spks: 2
  permute: true
  zero_mean: false

trainer_conf:
  optimizer: "adam"
  optimizer_kwargs:
    lr: 1.0e-3
    weight_decay: 1.0e-5
  lr_scheduler_kwargs:
    min_lr: 1.0e-8
    patience: 1
    factor: 0.5
  clip_gradient: 10
  no_impr: 6
  no_impr_thres: 0.1

data_conf:
  fmt: "se@chunk"
  loader:
    chunk_size: 32000
    sr: 8000
  train:
    mix_scp: "data/wsj0_2mix/tr/mix.scp"
    ref_scp: "data/wsj0_2mix/tr/spk1.scp,data/wsj0_2mix/tr/spk2.scp"
  valid:
    mix_scp: "data/wsj0_2mix/cv/mix.scp"
    ref_scp: "data/wsj0_2mix/cv/spk1.scp,data/wsj0_2mix/cv/spk2.scp"
